#!/usr/bin/env python3
"""Render the release statistics the README shows.

Reads the cloc JSON the stats workflow wrote, emits one Shields "endpoint"
badge per metric under .github/badges/, and rewrites the marker-delimited
block in README.md. CI-only, release-tag-only: the numbers and the release
label are stamped together on purpose, so a failed run leaves the previous
release named rather than a label that claims numbers it does not have.

The badge JSON and the README block are the only outputs; the workflow's
exhaustiveness check is what guarantees the five buckets partition every Go
line in the repository.
"""

import json
import os
import pathlib
import re

KEYS = ("code", "comment", "blank", "nFiles")
BUCKETS = ("lib", "test", "bench", "tool", "examples")
BUCKET_ROWS = (
    ("Library", "lib"),
    ("Tests", "test"),
    ("Benchmarks", "bench"),
    ("Tooling", "tool"),
    ("Examples", "examples"),
)

README_MARKER_RE = re.compile(r"<!-- stats:begin.*?stats:end -->", re.S)


def sums(path):
    """cloc --json -> {"code": n, "comment": n, "blank": n, "nFiles": n}."""
    with open(path, encoding="utf-8") as handle:
        total = json.load(handle).get("SUM", {})
    return {key: int(total.get(key, 0) or 0) for key in KEYS}


def load_buckets(stats_dir):
    """Read the five cloc buckets the workflow wrote under stats_dir."""
    directory = pathlib.Path(stats_dir)
    return {name: sums(directory / f"{name}.json") for name in BUCKETS}


def total_of(buckets):
    """Sum the buckets: every Go line in the repository is in exactly one."""
    return {key: sum(bucket[key] for bucket in buckets.values()) for key in KEYS}


def coverage_color(coverage):
    if coverage == "100.0":
        return "brightgreen"
    try:
        value = float(coverage)
    except ValueError:
        return "red"
    return "green" if value >= 90 else "red"


def badge(label, message, color):
    return {
        "schemaVersion": 1,
        "label": label,
        "message": message,
        "color": color,
        "cacheSeconds": 300,
    }


def render_badges(label, coverage, buckets):
    total = total_of(buckets)
    return {
        "coverage": badge(
            f"coverage ({label})", f"{coverage}%", coverage_color(coverage)
        ),
        "loc-library": badge(
            f"library LOC ({label})", f"{buckets['lib']['code']:,}", "blue"
        ),
        "loc-tests": badge(
            f"test LOC ({label})", f"{buckets['test']['code']:,}", "blue"
        ),
        "loc-bench": badge(
            f"benchmark LOC ({label})", f"{buckets['bench']['code']:,}", "blue"
        ),
        "loc-tooling": badge(
            f"tooling LOC ({label})", f"{buckets['tool']['code']:,}", "blue"
        ),
        "loc-examples": badge(
            f"examples LOC ({label})", f"{buckets['examples']['code']:,}", "blue"
        ),
        "loc-total": badge(f"total LOC ({label})", f"{total['code']:,}", "blue"),
    }


def render_block(label, coverage, buckets):
    total = total_of(buckets)

    def row(name, stats):
        return (
            f"| {name} | {stats['code']:,} | {stats['comment']:,} | "
            f"{stats['blank']:,} | {stats['nFiles']} |"
        )

    lines = [
        "<!-- stats:begin — generated by .github/workflows/stats.yml; do not edit by hand -->",
        "| | code | comment | blank | files |",
        "|---|---:|---:|---:|---:|",
        *(row(name, buckets[key]) for name, key in BUCKET_ROWS),
        row("**Total**", total),
        "",
        "_Total is every Go line in the repository; the buckets are disjoint and "
        "the workflow fails if they stop covering it._",
        "",
        f"Statement coverage **{coverage}%** · statistics updated at **{label}**.",
        "<!-- stats:end -->",
    ]
    return "\n".join(lines)


def replace_block(text, block):
    """Replace the marker-delimited stats block, or fail if it is missing."""
    if README_MARKER_RE.search(text) is None:
        raise SystemExit(
            "README.md has no <!-- stats:begin --> marker: add the block once "
            "by hand, then this job keeps it fresh"
        )
    return README_MARKER_RE.sub(lambda _: block, text)


def write_outputs(root, stats_dir, label, coverage):
    buckets = load_buckets(stats_dir)
    root = pathlib.Path(root)
    readme = root / "README.md"
    block = render_block(label, coverage, buckets)
    # Validate the marker before writing any badge, so a misconfigured README
    # cannot leave a half-updated .github/badges behind.
    new_text = replace_block(readme.read_text(encoding="utf-8"), block)
    badges = root / ".github" / "badges"
    badges.mkdir(parents=True, exist_ok=True)
    for name, data in render_badges(label, coverage, buckets).items():
        (badges / f"{name}.json").write_text(
            json.dumps(data, indent=2) + "\n", encoding="utf-8"
        )
    readme.write_text(new_text, encoding="utf-8")


def main():
    write_outputs(
        os.environ.get("REPO_ROOT", "."),
        os.environ.get("STATS_DIR", "/tmp"),
        os.environ["LABEL"],
        os.environ["TOTAL"],
    )


if __name__ == "__main__":
    main()
